backends/zoneinfo.py: Skip using the "Factory" timezone
Referencing the "Factory" timezone can lead to ValueError exceptions on some systems, e.g. FreeBSD, if the system zoneinfo database is used:

ValueError: Invalid STD format in b'<Local time zone must be set--use tzsetup>0'

Thus drop the "Factory" timezone from the sets before iterating over them to avoid the aforementioned issue.